{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.123.742.0 (23.11)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"updated_file\"]"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "DynamicImprovement": "HighConfidence",
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "extendedProperties": [
      {
        "name": "SQLBI_BRAVO_ManageDatesConfiguration",
        "type": "json",
        "value": {
          "name": "Config-01",
          "autoNaming": 1,
          "autoScan": 127,
          "dateAvailable": true,
          "dateEnabled": true,
          "dateReferenceTableName": "DateAutoTemplate",
          "dateReferenceTableValidation": 1,
          "dateTableName": "Date",
          "dateTableValidation": 1,
          "defaults": {
            "firstDayOfWeek": 0
          },
          "description": "Standard gregorian calendar",
          "exceptTablesColumns": [],
          "holidaysAvailable": true,
          "holidaysDefinitionTableName": "HolidaysDefinition",
          "holidaysDefinitionTableValidation": 0,
          "holidaysEnabled": false,
          "holidaysTableName": "Holidays",
          "holidaysTableValidation": 0,
          "isCurrent": false,
          "isCustom": false,
          "isoCountry": "US",
          "onlyTablesColumns": [],
          "targetMeasures": [],
          "templateUri": "file:///C:/Users/Yoga/AppData/Local/Bravo/.temp/ManageDates/Templates/Config-01.template.json",
          "timeIntelligenceAvailable": true,
          "timeIntelligenceEnabled": true
        }
      }
    ],
    "relationships": [
      {
        "name": "128fe0cd-4584-49c5-bc1c-717ed3c89446",
        "fromColumn": "Date",
        "fromTable": "updated_file",
        "toColumn": "Date",
        "toTable": "Date"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "updated_file",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "track_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "61db5432-e784-4332-a3f6-60a992bc7935",
            "sourceColumn": "track_name",
            "summarizeBy": "none"
          },
          {
            "name": "artist_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2f1c97a5-04ef-4294-9ab2-534675ff7343",
            "sourceColumn": "artist_name",
            "summarizeBy": "none"
          },
          {
            "name": "artist_count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f77ee157-53d3-46f3-8b03-4b55b6e1650f",
            "sourceColumn": "artist_count",
            "summarizeBy": "sum"
          },
          {
            "name": "released_year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2d140a20-78df-40b9-b33f-ce276822c52c",
            "sourceColumn": "released_year",
            "summarizeBy": "sum"
          },
          {
            "name": "released_month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5f8bf77d-e70c-4603-a6ee-7550cd34da4b",
            "sourceColumn": "released_month",
            "summarizeBy": "sum"
          },
          {
            "name": "released_day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d0f7dfce-baf1-4e1c-84df-317ceb6a3237",
            "sourceColumn": "released_day",
            "summarizeBy": "sum"
          },
          {
            "name": "in_spotify_playlists",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "77becfc9-fea6-49e9-abe9-cf34627b5b05",
            "sourceColumn": "in_spotify_playlists",
            "summarizeBy": "sum"
          },
          {
            "name": "in_spotify_charts",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d28f94e4-7ad1-4bec-ac37-9c3971cdd152",
            "sourceColumn": "in_spotify_charts",
            "summarizeBy": "sum"
          },
          {
            "name": "streams",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8e40569e-de8c-4723-82b8-55ecfd8d404c",
            "sourceColumn": "streams",
            "summarizeBy": "sum"
          },
          {
            "name": "in_apple_playlists",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "cb32dab5-f317-4470-ab06-d9e3a3ba3888",
            "sourceColumn": "in_apple_playlists",
            "summarizeBy": "sum"
          },
          {
            "name": "in_apple_charts",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f9ca5162-1ff2-4b81-a7f5-037b92b3bb17",
            "sourceColumn": "in_apple_charts",
            "summarizeBy": "sum"
          },
          {
            "name": "in_deezer_playlists",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5feee0a5-f41f-40bd-b23a-511b7b4037e4",
            "sourceColumn": "in_deezer_playlists",
            "summarizeBy": "sum"
          },
          {
            "name": "in_deezer_charts",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "41a36c61-c30f-4731-9ece-34c49bddf76a",
            "sourceColumn": "in_deezer_charts",
            "summarizeBy": "sum"
          },
          {
            "name": "in_shazam_charts",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d659622f-e262-4015-ab40-2d6114cce8f1",
            "sourceColumn": "in_shazam_charts",
            "summarizeBy": "sum"
          },
          {
            "name": "bpm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b29122dd-b6b2-4244-97b3-66e92ced5c87",
            "sourceColumn": "bpm",
            "summarizeBy": "sum"
          },
          {
            "name": "key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1b4a9a00-c30c-4691-8aed-41fef1673a6f",
            "sourceColumn": "key",
            "summarizeBy": "none"
          },
          {
            "name": "mode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d8d3149e-c9f6-467c-8b9d-804fd3080f9c",
            "sourceColumn": "mode",
            "summarizeBy": "none"
          },
          {
            "name": "danceability_%",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ec86a38c-eb84-4b69-93cb-bea3222a5340",
            "sourceColumn": "danceability_%",
            "summarizeBy": "sum"
          },
          {
            "name": "valence_%",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f6bd99d4-31e5-4112-9d56-45f9b7208cac",
            "sourceColumn": "valence_%",
            "summarizeBy": "sum"
          },
          {
            "name": "energy_%",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0e4ec5fd-f32f-45a3-8634-aebc25d05f1a",
            "sourceColumn": "energy_%",
            "summarizeBy": "sum"
          },
          {
            "name": "acousticness_%",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0938b063-c555-4333-aaf8-bd406aed9ccb",
            "sourceColumn": "acousticness_%",
            "summarizeBy": "sum"
          },
          {
            "name": "instrumentalness_%",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8a252bae-27e0-4518-9983-9aefda59343b",
            "sourceColumn": "instrumentalness_%",
            "summarizeBy": "sum"
          },
          {
            "name": "liveness_%",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "789578aa-16c0-44e9-9ccd-e92e3a3d3d48",
            "sourceColumn": "liveness_%",
            "summarizeBy": "sum"
          },
          {
            "name": "speechiness_%",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4248492d-97e3-45dc-ab4c-396dff3fa6c3",
            "sourceColumn": "speechiness_%",
            "summarizeBy": "sum"
          },
          {
            "name": "cover_url",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "ImageUrl",
            "dataType": "string",
            "lineageTag": "2fdd9625-fedb-4371-be0f-6952475f7505",
            "sourceColumn": "cover_url",
            "summarizeBy": "none"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "dateTime",
            "expression": "DATE([released_year],updated_file[released_month],updated_file[released_day])",
            "formatString": "m/d/yyyy",
            "isDataTypeInferred": true,
            "lineageTag": "a9bc990a-eb95-43da-bf56-b526a6244ac9",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "196e2ac1-5850-49ac-b1d2-59ca4c76f24a",
        "measures": [
          {
            "name": "Max streams",
            "expression": "MAX(updated_file[streams])",
            "formatString": "0",
            "lineageTag": "2d0a1a52-5ba7-43c8-8ed0-298750f41803"
          },
          {
            "name": "Top song streams",
            "expression": "CALCULATE(SUM(updated_file[streams]),updated_file[streams]= MAX(updated_file[streams]))",
            "formatString": "0",
            "lineageTag": "2730a802-9c91-4f6b-ab5f-f889084b4bf7"
          },
          {
            "name": "Average stream per year",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE( AVERAGE(updated_file[streams]),ALLEXCEPT(updated_file,'Date'[Year]))",
            "lineageTag": "c848071e-cfc3-47b1-9505-b2786699f450"
          },
          {
            "name": "Top song vs avg val",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "DIVIDE([Top song streams]-[Average stream per year], [Average stream per year])",
            "lineageTag": "df6f1655-c1e7-467b-abde-725c97c885e4"
          },
          {
            "name": "Top song vs AVG",
            "expression": [
              "VAR x = [Top song vs avg val] RETURN",
              " IF(x>0, FORMAT(x,\"#.0%\") & \" \" & UNICHAR(9650), FORMAT(x,\"#.0%\") & \" \" & UNICHAR(9660))"
            ],
            "lineageTag": "518c4716-2bbc-4be7-867c-dd61dedd73be"
          },
          {
            "name": "html",
            "expression": [
              "",
              "var x= CALCULATE( MAX(updated_file[cover_url]), updated_file[streams]= MAX(updated_file[streams])",
              ")",
              "return",
              "\"",
              "<!DOCTYPE html>",
              "<html lang='en'>",
              "<head>",
              "<meta charset='UTF-8'>",
              "<title>Image Cropping</title>",
              "<style>",
              ".image-container {",
              "  width: 480px; /* Width of the container */",
              "  height: 123px; /* Height of the container */",
              "  overflow: hidden; /* Hide parts of the image that don't fit */",
              "  border-radius: 15px; /* Rounded corners */",
              "  position: relative; /* Relative positioning for the child element */",
              "}",
              "",
              ".image {",
              "  object-fit: cover; /* Cover the entire container */",
              "  object-position: center; /* Center the image */",
              "  width: 100%; /* Full width */",
              "  height: 100%; /* Full height */",
              "}",
              "</style>",
              "</head>",
              "<body>",
              "<div class='image-container'>",
              "  <img src='\"&x&\"' alt='Album Cover' class='image'>",
              "</div>",
              "</body>",
              "</html>",
              "\""
            ],
            "lineageTag": "362b0a2a-c107-4326-b210-326a0a7f464f"
          },
          {
            "name": "percent_val",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "AVERAGE(updated_file[energy_%])",
            "lineageTag": "75b3743a-507b-4bee-9e40-488ea3b40794"
          },
          {
            "name": "tracks",
            "expression": "COUNT(updated_file[track_name])",
            "formatString": "0",
            "lineageTag": "1cf26d05-00f5-47a7-aa86-1e81d2dd0dca"
          }
        ],
        "partitions": [
          {
            "name": "updated_file",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\Yoga\\OneDrive\\Desktop\\spotify\\updated_file.csv\"),[Delimiter=\",\", Columns=25, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"track_name\", type text}, {\"artist_name\", type text}, {\"artist_count\", Int64.Type}, {\"released_year\", Int64.Type}, {\"released_month\", Int64.Type}, {\"released_day\", Int64.Type}, {\"in_spotify_playlists\", Int64.Type}, {\"in_spotify_charts\", Int64.Type}, {\"streams\", Int64.Type}, {\"in_apple_playlists\", Int64.Type}, {\"in_apple_charts\", Int64.Type}, {\"in_deezer_playlists\", Int64.Type}, {\"in_deezer_charts\", Int64.Type}, {\"in_shazam_charts\", Int64.Type}, {\"bpm\", Int64.Type}, {\"key\", type text}, {\"mode\", type text}, {\"danceability_%\", Int64.Type}, {\"valence_%\", Int64.Type}, {\"energy_%\", Int64.Type}, {\"acousticness_%\", Int64.Type}, {\"instrumentalness_%\", Int64.Type}, {\"liveness_%\", Int64.Type}, {\"speechiness_%\", Int64.Type}, {\"cover_url\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateAutoTemplate",
        "annotations": [
          {
            "name": "SQLBI_Template",
            "value": "Dates"
          },
          {
            "name": "SQLBI_TemplateTable",
            "value": "DateAutoTemplate"
          },
          {
            "name": "SQLBI_CalendarType",
            "value": "Calendar"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SQLBI_AttributeTypes",
                "value": "Date"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "m/d/yyyy",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isKey": true,
            "isNameInferred": true,
            "lineageTag": "082e0607-a5e4-40ee-9f3a-d90eee39b8ab",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "dataCategory": "Years",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "3bb85c80-4a4d-421c-8958-a6d8da9a2e1e",
            "sourceColumn": "[Year]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year Quarter Number",
            "dataCategory": "Quarters",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "95589645-6c64-4433-a9c8-6e534bdc5dfd",
            "sourceColumn": "[Year Quarter Number]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year Quarter",
            "dataCategory": "Quarters",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "862c38eb-aa6c-4646-a220-94ceb6366a1e",
            "sortByColumn": "Year Quarter Number",
            "sourceColumn": "[Year Quarter]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Quarter",
            "dataCategory": "QuarterOfYear",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "3053a03f-0147-471f-8389-a715b8f60e24",
            "sourceColumn": "[Quarter]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year Month",
            "dataCategory": "Months",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "c888a778-d051-4b1b-b652-ba12a4293793",
            "sortByColumn": "Year Month Number",
            "sourceColumn": "[Year Month]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year Month Number",
            "dataCategory": "Months",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "57bb63cf-66ff-42b6-9444-bd6aacd7ba27",
            "sourceColumn": "[Year Month Number]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Month",
            "dataCategory": "MonthOfYear",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "33cb1769-df2b-4520-9590-cf12047ace4a",
            "sortByColumn": "Month Number",
            "sourceColumn": "[Month]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Month Number",
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "ae9358b5-6fc1-471e-a35f-f001ce3ccac0",
            "sourceColumn": "[Month Number]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Day of Week Number",
            "annotations": [
              {
                "name": "SQLBI_AttributeTypes",
                "value": "DayOfWeek"
              },
              {
                "name": "SQLBI_FilterSafe",
                "value": "True"
              }
            ],
            "dataCategory": "DayOfWeek",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "543e3058-abf5-4114-9f38-dc628e22c557",
            "sourceColumn": "[Day of Week Number]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Day of Week",
            "annotations": [
              {
                "name": "SQLBI_FilterSafe",
                "value": "True"
              }
            ],
            "dataCategory": "DayOfWeek",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "43f40fcc-b657-4892-8438-b7279645c9be",
            "sortByColumn": "Day of Week Number",
            "sourceColumn": "[Day of Week]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "DateWithTransactions",
            "annotations": [
              {
                "name": "SQLBI_AttributeTypes",
                "value": "DateDuration"
              }
            ],
            "dataType": "boolean",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "9ac52352-698d-4140-ae28-ea92d56b5456",
            "sourceColumn": "[DateWithTransactions]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "dataCategory": "Time",
        "hierarchies": [
          {
            "name": "Calendar",
            "isHidden": true,
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "9689029d-8632-4705-a2be-046813c51ce4",
                "ordinal": 0
              },
              {
                "name": "Month",
                "column": "Year Month",
                "lineageTag": "25324059-d86c-4da5-b0ce-c1ed2ceb3949",
                "ordinal": 1
              },
              {
                "name": "Date",
                "column": "Date",
                "lineageTag": "c606af9e-1665-441d-9523-96a057d465b8",
                "ordinal": 2
              }
            ],
            "lineageTag": "67c0d8d1-a130-4ac1-b36d-f47ed491666d"
          }
        ],
        "isHidden": true,
        "lineageTag": "bdabdebc-9e10-4d4b-90f6-b9eaa4e1cda4",
        "partitions": [
          {
            "name": "DateAutoTemplate",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "--  ",
                "--     Configuration",
                "--  ",
                "VAR __FirstDayOfWeek = 0",
                "----------------------------------------",
                "VAR __WeekDayCalculationType = IF ( __FirstDayOfWeek = 0, 7, __FirstDayOfWeek ) + 10",
                "VAR __Calendar = ",
                "    VAR __FirstYear = YEAR ( MINX ( { MIN ( 'updated_file'[Date] ) }, ''[Value] ) )",
                "    VAR __LastYear =  YEAR ( MAXX ( { MAX ( 'updated_file'[Date] ) }, ''[Value] ) )",
                "    RETURN CALENDAR (",
                "        DATE ( __FirstYear, 1, 1 ),",
                "        DATE ( __LastYear, 12, 31 )",
                "    )",
                "VAR __Step3 = ",
                "    GENERATE (",
                "        __Calendar,",
                "        VAR __IsStandardLocale = IF ( FORMAT( DATE( 2000, 1, 1 ), \"oooo\" ) = \"oooo\", TRUE, FALSE )",
                "        VAR __MonthFormatString = IF( __IsStandardLocale, \"mmm\", \"ooo\" )",
                "        VAR __DayFormatString = IF( __IsStandardLocale, \"ddd\", \"aaa\" )",
                "        VAR __LastTransactionDate = MAXX ( { MAX ( 'updated_file'[Date] ) }, ''[Value] )",
                "        VAR __Date = [Date]",
                "        VAR __YearNumber = YEAR ( __Date )",
                "        VAR __QuarterNumber = QUARTER ( __Date )",
                "        VAR __YearQuarterNumber = CONVERT ( __YearNumber * 4 + __QuarterNumber - 1, INTEGER )",
                "        VAR __MonthNumber = MONTH ( __Date )",
                "        VAR __WeekDayNumber = WEEKDAY ( __Date, __WeekDayCalculationType )",
                "        VAR __WeekDay = FORMAT ( __Date, __DayFormatString )",
                "        RETURN ROW ( ",
                "            \"Year\", __YearNumber,",
                "            \"Year Quarter Number\", __YearQuarterNumber,",
                "            \"Year Quarter\", FORMAT ( __QuarterNumber, \"\\Q0\" ) & \"-\" & FORMAT ( __YearNumber, \"0000\" ),",
                "            \"Quarter\", FORMAT( __QuarterNumber, \"\\Q0\" ),",
                "            \"Year Month\", FORMAT ( __Date, __MonthFormatString & \" yyyy\" ),",
                "            \"Year Month Number\", __YearNumber * 12 + __MonthNumber - 1,",
                "            \"Month\", FORMAT ( __Date, __MonthFormatString ),",
                "            \"Month Number\", __MonthNumber,",
                "            \"Day of Week Number\", __WeekDayNumber,",
                "            \"Day of Week\", __WeekDay,",
                "            \"DateWithTransactions\", __Date <= __LastTransactionDate ",
                "        )",
                "    )",
                "RETURN",
                "    __Step3"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Date",
        "annotations": [
          {
            "name": "SQLBI_Template",
            "value": "Dates"
          },
          {
            "name": "SQLBI_TemplateTable",
            "value": "Date"
          },
          {
            "name": "SQLBI_CalendarType",
            "value": "Calendar"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SQLBI_AttributeTypes",
                "value": "Date"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "m/d/yyyy",
            "isDataTypeInferred": true,
            "isKey": true,
            "isNameInferred": true,
            "lineageTag": "449344e4-3934-4970-9a06-6075a84ac8c8",
            "sourceColumn": "DateAutoTemplate[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "dataCategory": "Years",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "33bd1d0b-a716-4ce8-8e54-cac591c6b790",
            "sourceColumn": "DateAutoTemplate[Year]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year Quarter Number",
            "dataCategory": "Quarters",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "d7721c8a-3436-4ee2-aa5c-c3dac3347157",
            "sourceColumn": "DateAutoTemplate[Year Quarter Number]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year Quarter",
            "dataCategory": "Quarters",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "128cfab5-1c22-41ce-bdf2-e7431c9cf688",
            "sortByColumn": "Year Quarter Number",
            "sourceColumn": "DateAutoTemplate[Year Quarter]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Quarter",
            "dataCategory": "QuarterOfYear",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "ade7ef8b-f147-4ae8-9ba2-513d6060bdfc",
            "sourceColumn": "DateAutoTemplate[Quarter]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year Month",
            "dataCategory": "Months",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "f40c05bd-e41d-442a-8401-e8fa81713a9c",
            "sortByColumn": "Year Month Number",
            "sourceColumn": "DateAutoTemplate[Year Month]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year Month Number",
            "dataCategory": "Months",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "bc04dd9a-b945-4e20-8caa-ad260d8f5f63",
            "sourceColumn": "DateAutoTemplate[Year Month Number]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Month",
            "dataCategory": "MonthOfYear",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "1b73eecd-a75b-42c7-a150-98b4304cc6ed",
            "sortByColumn": "Month Number",
            "sourceColumn": "DateAutoTemplate[Month]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Month Number",
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "cee450b5-f7a3-4445-a6bf-d1538aeacad9",
            "sourceColumn": "DateAutoTemplate[Month Number]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Day of Week Number",
            "annotations": [
              {
                "name": "SQLBI_AttributeTypes",
                "value": "DayOfWeek"
              },
              {
                "name": "SQLBI_FilterSafe",
                "value": "True"
              }
            ],
            "dataCategory": "DayOfWeek",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "591412ff-6952-4e2e-a63d-5bf2cb422e6a",
            "sourceColumn": "DateAutoTemplate[Day of Week Number]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Day of Week",
            "annotations": [
              {
                "name": "SQLBI_FilterSafe",
                "value": "True"
              }
            ],
            "dataCategory": "DayOfWeek",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "1386dbad-42ca-4f8a-9466-6c611a5196c6",
            "sortByColumn": "Day of Week Number",
            "sourceColumn": "DateAutoTemplate[Day of Week]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "DateWithTransactions",
            "annotations": [
              {
                "name": "SQLBI_AttributeTypes",
                "value": "DateDuration"
              }
            ],
            "dataType": "boolean",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "22920aee-e9af-4ee9-8651-f301c7f1b148",
            "sourceColumn": "DateAutoTemplate[DateWithTransactions]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "dataCategory": "Time",
        "hierarchies": [
          {
            "name": "Calendar",
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "0c1b3f65-af41-4db2-815e-d19d5b0b1c4e",
                "ordinal": 0
              },
              {
                "name": "Month",
                "column": "Year Month",
                "lineageTag": "2d661dd1-5b9d-4494-999a-e45bb3c1739f",
                "ordinal": 1
              },
              {
                "name": "Date",
                "column": "Date",
                "lineageTag": "cb4693da-8d04-49b4-9e61-6a8f117f8a95",
                "ordinal": 2
              }
            ],
            "lineageTag": "f743302a-26ad-4469-85de-b350b374c313"
          }
        ],
        "lineageTag": "b8533dc9-8bc9-4156-a91c-709378246fac",
        "measures": [
          {
            "name": "_ShowValueForDates",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Hidden Time Intelligence",
            "expression": [
              "",
              "VAR __LastDateWithData =",
              "    CALCULATE (",
              "        MAXX ( { MAX ( 'updated_file'[Date] ) }, ''[Value] ),",
              "        REMOVEFILTERS ()",
              "    )",
              "VAR __FirstDateVisible =",
              "    MIN ( 'Date'[Date] )",
              "VAR __Result =",
              "    __FirstDateVisible <= __LastDateWithData",
              "RETURN",
              "    __Result"
            ],
            "isHidden": true,
            "lineageTag": "8fee4572-7a3a-40cc-b485-e288ffd30573"
          },
          {
            "name": "track",
            "lineageTag": "c8b04b5e-1d82-4b73-80d1-bdbc8d50c408"
          }
        ],
        "partitions": [
          {
            "name": "Date",
            "mode": "import",
            "source": {
              "expression": "DateAutoTemplate",
              "type": "calculated"
            }
          }
        ]
      }
    ]
  }
}